#+title: YADC: Yet Another DVSA Checker

YADC is yet another checker for driving cancellations in the UK.

- why another? :: Because all the code I found on github doesn't work with the
  latest anti-bot protections on dvsa.  Besides, it was all rather
  spaghettified.  YADC is, I hope a little cleaner and more modular.  It should
  be easier to modify down the line.
- why a bot? :: Because I can't get a driving test.  Note that I /do not think/
  this solution is remotely ideal.  See the appeal below.
- will you maintain this? :: Not if I get a test and pass.  But hopefully it
  should be a better framework for the next generation to come along and do the
  same.

** Appeal to DVSA
   The current situation is a mess.  Because of the pandemic, there are no tests
   for months; that is not your fault.  So we are all forced either to wait for
   months, or to book a last-minute cancellation. But we can't do that, because
   all the companies using bots to find tests snatch them up.  So we all use
   those companies; and then DVSA's website becomes even more useless.  There
   are two *easy* solutions you could adopt:

   - Add an auto-booking with queue feature to the website.  Once a test is
     booked you get to specify criteria for a better test, and enter in a queue.
     When you rise to the top of that queue, you get whatever matches reserved
     for you.  In other words, implement the third-party solution yourself.  I
     would gladly pay a reasonable sum for it.  And the third-party firms will
     go out of business and stop spamming your website.

   - Add an API, and charge for access.  That way the third parties will use the
     API.  You can release tests to the API after x minutes to give humans a
     chance as well.  You can go after anyone who tries to use a bot to get
     round the limit, and providing your API is reasonable, nobody will mind.

   Instead of these, you make the already useless website even harder to use.
   Bot protection is an uphill battle.  So is bot developing.  The only people
   who profit from this are companies like google (via chrome/chromium).
  
  


